name: Metrics
on:
  schedule:
    - cron: "30 18 * * 6"   # Runs once a week (Sunday 12:00 AM IST)
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: RACHAMADUGUSIVASANKAR
          template: classic
          base: header, repositories, community
          config_timezone: Asia/Calcutta

          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_threshold: 0%
          plugin_languages_categories: markup, programming

          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_threshold: C

          plugin_leetcode: yes
          plugin_leetcode_user: 234G1A33G4
          plugin_leetcode_sections: solved
          plugin_leetcode_limit_skills: 10
          plugin_leetcode_limit_recent: 2

          plugin_followup: yes
          plugin_followup_sections: repositories

          plugin_reactions: yes
          plugin_reactions_display: absolute
